# Generated by Django 3.2.6 on 2021-09-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default=3, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='number',
            field=models.IntegerField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
